### ISSUE TITLE
Autoencoder not found

### ISSUE THREAD

**Issue by liusiping10** [ArminMasoumian/GCNDepth#1]
from ..mono_autoencoder.encoder import Encoder not found this module

**Comment by ArminMasoumian** [comment]
Thank you for your reminder, I updated the code with mono_autoencoder.

**Comment by daniele-salerno** [comment]
![image](https://user-images.githubusercontent.com/45399301/146561189-320e20e7-cbf0-406b-84e9-54e7d84855f0.png)

similar problem here

**Comment by ArminMasoumian** [comment]
> ![image](https://user-images.githubusercontent.com/45399301/146561189-320e20e7-cbf0-406b-84e9-54e7d84855f0.png)
> 
> similar problem here

All models are updated now, thank you for your reminder.
