### ISSUE TITLE
Plz help me with this issue during running run.py file

### ISSUE THREAD

**Issue by Affan-Abbas8** [ArminMasoumian/GCNDepth#10]
FileNotFoundError: [Errno 2] No such file or directory: '/run/media/armin/DATA/GCNDepth/Models/resnet50.pth'

**Comment by ArminMasoumian** [comment]
After downloading the pre-trained backbones, paste them into your directory path.
Also, you need to replace the config file directories in "cfg_kitti_fm.py" with your own directories.
