### ISSUE TITLE
plz help

### ISSUE THREAD

**Issue by Affan-Abbas8** [ArminMasoumian/GCNDepth#12]
thanks for your response.
Yes, now I again installed all the requirements and the issue changed now.
Here is the screen shot.
Plz take a look and let me know about it.
![11](https://user-images.githubusercontent.com/119195312/205162039-4b303100-050a-47da-9cea-90a29959dc71.PNG)

**Comment by Affan-Abbas8** [comment]
Should I change something here as well?
![22](https://user-images.githubusercontent.com/119195312/205162167-28c1d304-49a5-402b-a6c2-e7df2f39f15e.PNG)

**Comment by Affan-Abbas8** [comment]
![33](https://user-images.githubusercontent.com/119195312/205162188-2d954c1f-78e1-4279-abb6-4efb305b5f10.PNG)

and should I have to change the path in config_kitti_autoencder too?

**Comment by ArminMasoumian** [comment]
Yes, you need to change the path to your directories, the first paths are for the raw Kitti dataset and the second path is for ResNet backbones.
