### ISSUE TITLE
How to change the batch_size?

### ISSUE THREAD

**Issue by buster-zbb** [ArminMasoumian/GCNDepth#13]
Hello, when I try to train your code, CUDA out of memory. I want to adjust the batch_ size, but the parameter cannot be found in the code.

**Comment by ArminMasoumian** [comment]
In cfg_kitti_fm.py, you can change the "log_config = dict(interval=10," for batch size, also be sure "IMGS_PER_GPU" in the same file is set to 1.

All parameters are set in this config file.
