### ISSUE TITLE
data set issue

### ISSUE THREAD

**Issue by Affan-Abbas8** [ArminMasoumian/GCNDepth#14]
How can I download kitty data set bro?
and I read that it needs 175 Gb of free space. is that true?

**Comment by Affan-Abbas8** [comment]
and how long will it take for the training?

**Comment by ArminMasoumian** [comment]
Here you can find how to download the Kitti dataset and unzip and split it:
https://github.com/nianticlabs/monodepth2

Here is the code to download the Kitti raw dataset:
wget -i splits/kitti_archives_to_download.txt -P kitti_data/

Yes, the Kitti dataset is 175Gb, for us with GTX 1080TI GPU it took 11 days for 20 epochs.

**Comment by Affan-Abbas8** [comment]
okay thank you.
is there any way to reduce the dataset size?
