### ISSUE TITLE
Some Confusions Regarding Your Paper

### ISSUE THREAD

**Issue by echo0916** [ArminMasoumian/GCNDepth#15]
Hello, I have some confusion regarding the paper you published in the journal _Neurocomputing_. 

Q1: In Fig.3, you indicated that during the training phase D is generated by Source Frame (I_s), but in other studies (e.g. Monodepth2), it is stated that D is generated by the Target Frame (I_t). The generation of I_{s→t} follows the equation: I_{s→t} = I_s[𝑝𝑟𝑜𝑗(𝑟𝑒𝑝𝑟𝑜𝑗(I_t, D_t, T_{t→s}), 𝐾)]. I'm curious why you chose to represent it in this way.

Q2: In Fig.3, R & T are generated through the decoder of Posenet, but you only drew the encoder part. May I ask why?

If you can help me clarify my doubts, that would be great.

**Comment by ArminMasoumian** [comment]
> Hello, I have some confusion regarding the paper you published in the journal _Neurocomputing_.
> 
> Q1: In Fig.3, you indicated that during the training phase D is generated by Source Frame (I_s), but in other studies (e.g. Monodepth2), it is stated that D is generated by the Target Frame (I_t). The generation of I_{s→t} follows the equation: I_{s→t} = I_s[𝑝𝑟𝑜𝑗(𝑟𝑒𝑝𝑟𝑜𝑗(I_t, D_t, T_{t→s}), 𝐾)]. I'm curious why you chose to represent it in this way.
> 
> Q2: In Fig.3, R & T are generated through the decoder of Posenet, but you only drew the encoder part. May I ask why?
> 
> If you can help me clarify my doubts, that would be great.

You're correct, our figure is confusing. To clarify, the predicted depth is generated from the target image. However, it's possible to generate the depth map using both the source and target images.

In the traditional approach, the target image is used to generate the ground-truth depth map, and the source image is used as input to the network to predict the depth map. Alternatively, the source image can be used to generate the ground-truth depth map, and the target image can be used as input to the network to predict the depth map.

Regarding the second question, we utilized an autoencoder model for DepthNet and a normal estimator for PoseNet. Therefore, we decided to draw two different shapes to display that these two encoder-decoder models are different.

**Comment by echo0916** [comment]
> > Hello, I have some confusion regarding the paper you published in the journal _Neurocomputing_.
> > Q1: In Fig.3, you indicated that during the training phase D is generated by Source Frame (I_s), but in other studies (e.g. Monodepth2), it is stated that D is generated by the Target Frame (I_t). The generation of I_{s→t} follows the equation: I_{s→t} = I_s[𝑝𝑟𝑜𝑗(𝑟𝑒𝑝𝑟𝑜𝑗(I_t, D_t, T_{t→s}), 𝐾)]. I'm curious why you chose to represent it in this way.
> > Q2: In Fig.3, R & T are generated through the decoder of Posenet, but you only drew the encoder part. May I ask why?
> > If you can help me clarify my doubts, that would be great.
> 
> You're correct, our figure is confusing. To clarify, the predicted depth is generated from the target image. However, it's possible to generate the depth map using both the source and target images.
> 
> In the traditional approach, the target image is used to generate the ground-truth depth map, and the source image is used as input to the network to predict the depth map. Alternatively, the source image can be used to generate the ground-truth depth map, and the target image can be used as input to the network to predict the depth map.
> 
> Regarding the second question, we utilized an autoencoder model for DepthNet and a normal estimator for PoseNet. Therefore, we decided to draw two different shapes to display that these two encoder-decoder models are different.

Thank you for your answer.
