### ISSUE TITLE
Where can I find these files?

### ISSUE THREAD

**Issue by ellery3** [ArminMasoumian/GCNDepth#18]
in ‘./config/cfh_kitti_fm.py' resnet50.pth & resnet18.pth & autoencoder.pth & gt_depths.npz

**Comment by ArminMasoumian** [comment]
> in ‘./config/cfh_kitti_fm.py' resnet50.pth & resnet18.pth & autoencoder.pth & gt_depths.npz

Autoencoder : https://drive.google.com/file/d/1ncAWUMvLq2ETMpG-7eI9qfILce_cPPfy/view
ResNet-18: https://download.pytorch.org/models/resnet18-5c106cde.pth
ResNet-50: https://download.pytorch.org/models/resnet50-19c8e357.pth
GT_Depths.npz: You can download the file ```export_gt_depth.py``` from [Monodepth2](https://github.com/nianticlabs/monodepth2), and then run ```python export_gt_depth.py --data_path kitti_data --split eigen``` to prepare the ground-truth. More information regarding the data preparation can be also found on their repo.
