### ISSUE TITLE
Can't run run.py

### ISSUE THREAD

**Issue by jeoseo** [ArminMasoumian/GCNDepth#2]
I seem to be unable to import from mono.apis. Is there something I missed from instructions?

![image](https://user-images.githubusercontent.com/50963152/152659274-cc7a6634-b532-4340-9d7a-617f3e746c7c.png)

**Comment by ArminMasoumian** [comment]
> The requirements.txt update fixed the issue with the torch version. However, which version of Pillow are you using?

We used the 6.2.2 version.

**Comment by jeoseo** [comment]
I still can't seem to import mono.apis... 
![image](https://user-images.githubusercontent.com/50963152/152847531-1f4d05e7-9468-4d6b-8272-8e0782e3af98.png)

**Comment by ArminMasoumian** [comment]
> I still can't seem to import mono.apis... ![image](https://user-images.githubusercontent.com/50963152/152847531-1f4d05e7-9468-4d6b-8272-8e0782e3af98.png)

It seems that your GPU is not set well. If you have more than 1 GPU, in the run.py file, change the number of GPUs in --nproc_per_node=1 and try again. If it did not solve, try to test it with 1 GPU.
