### ISSUE TITLE
explain the API

### ISSUE THREAD

**Issue by zsh1223** [ArminMasoumian/GCNDepth#21]
Hi, could you explain the inferenceinfer_singleimage.py，eval_depth_pp.py，draw_odometry.py mean anything?

![image](https://github.com/ArminMasoumian/GCNDepth/assets/130481211/8d3941ef-453e-40c9-8578-cc2c3ac8ea1f)

**Comment by zsh1223** [comment]
Thank you for your explanation of the API.
Is infer_singleimage.py useful for posenet networks? If useful, how does he work in infer_singleimage.py?

**Comment by ArminMasoumian** [comment]
> Thank you for your explanation of the API. Is infer_singleimage.py use the posenet networks? If use it, how does the posenet work in infer_singleimage.py?

Yes, we do use PoseNet in our network, and it plays a crucial role in generating depth images from a single picture. To achieve this, we require the necessary transposed information. For a detailed explanation, please refer to our paper at this link: https://www.sciencedirect.com/science/article/abs/pii/S0925231222013601.
