### ISSUE TITLE
missing euroc_ Dataset.py file

### ISSUE THREAD

**Issue by zsh1223** [ArminMasoumian/GCNDepth#22]
In the GCNDepth main/mono/datasets path, missing euroc_ Dataset.py file

![image](https://github.com/ArminMasoumian/GCNDepth/assets/130481211/6b942541-0189-471f-bce8-932a387a785d)
![image](https://github.com/ArminMasoumian/GCNDepth/assets/130481211/63b9ba71-3ac1-44e5-bdd6-c4d660445335)

**Comment by ArminMasoumian** [comment]
The missing "euroc_Dataset.py" file has been added to the GCNDepth repository in the GCNDepth-main/mono/datasets path.
