### ISSUE TITLE
This paper seems fake, There is no use of GCN what so ever !

### ISSUE THREAD

**Issue by Akash82228** [ArminMasoumian/GCNDepth#25]
This paper seems fake !

**Comment by ArminMasoumian** [comment]
In the mono/model/mono_fm/layers.py file, you can find the GraphConvolution and GCN classes. As for the usage of GCN in the Depth decoder, you can locate the code in mono/model/mono_fm/depth_decoder.py!

Next time, you should probably observe more carefully before opening an issue!
