### ISSUE TITLE
Why dont you add 5 layer in decoder depth? why don't expect Input's resolution == Output's resolution?

### ISSUE THREAD

**Issue by huynhhoanghuy** [ArminMasoumian/GCNDepth#5]
![image](https://user-images.githubusercontent.com/32119423/164147794-355230ad-a6c9-4b0c-a849-2aaeef95806d.png)

I mean, why you don't add the 5th layer with size == input size? I think if using interpolate in depth, it will take a risk.

**Comment by ArminMasoumian** [comment]
> ![image](https://user-images.githubusercontent.com/32119423/164147794-355230ad-a6c9-4b0c-a849-2aaeef95806d.png)
> 
> I mean, why you don't add the 5th layer with size == input size? I think if using interpolate in depth, it will take a risk.

Adding 5th layer will increase complexity of the model and because of the time consuming, we used only 4 layers.
