### ISSUE TITLE
The networks used for training model

### ISSUE THREAD

**Issue by Hazeline2018** [ArminMasoumian/GCNDepth#6]
Hello, thanks for the excellent work and sharing source codes. I'm working on mono-depth estimation for my robotic project and came across your work online. I saw two papers related to this git repo. one is [](https://arxiv.org/abs/2111.01715) and second one is [](https://arxiv.org/abs/2112.06782). 
I just quickly skimped through these two papers (not knowing too much details yet), and noticed that these two papers seem using different networks for training models. 
The 1st paper uses YOLOv5 for both training networks (object detection & depth estimation); while the 2nd paper uses ResNet-50 for object detection and ResNet-18 for depth estimation. Are I correct?
My question is what exactly networks are being used in this git repo?
Thanks
Terry

**Comment by ArminMasoumian** [comment]
Thank you for showing your interest in this paper.
There are two papers:

[GCNDepth: Self-supervised Monocular Depth Estimation based on Graph Convolutional Network](https://arxiv.org/abs/2112.06782)

This paper is about a depth prediction and has two sub-network: DepthNet and PoseNet. The pre-trained model of ResNet50 is used for DepthNet and the Pre-trained model ResNet18 is used for PoseNet.
This repository is for this paper and you will get the relative distance of the objects with this model.

[Absolute distance prediction based on deep learning object detection and monocular depth estimation models]

This is the second paper. In this paper, we estimated the absolute distance of each object. This model has two sub-network as well. The first network is GCNDepth (the whole model of the first paper, which is this repo) and the second subnetwork is famous YOLOv5 for object detection. You can find the YOLOv5 code in the below link: 

https://github.com/ultralytics/yolov5
