### ISSUE TITLE
I am getting this issue after running the run command. Plz tell the solution. Thanks

### ISSUE THREAD

**Issue by Affan-Abbas8** [ArminMasoumian/GCNDepth#9]
![issue](https://user-images.githubusercontent.com/119195312/204142159-21e33c83-2c0a-42fb-bc5b-3bb2acc48c95.jpg)

**Comment by ArminMasoumian** [comment]
Please download the pre-trained backbone from these links and paste it to the same directory path.

ResNet18: https://download.pytorch.org/models/resnet18-5c106cde.pth
ResnNet50: https://download.pytorch.org/models/resnet50-19c8e357.pth
